# Generated by Django 4.1.7 on 2023-04-26 06:34

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55)),
                ('subject', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='cartoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=50)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.CharField(max_length=255)),
                ('Release_Year', models.CharField(blank=True, max_length=55, null=True)),
                ('download_url', models.CharField(blank=True, max_length=300, null=True)),
                ('download_url1', models.CharField(blank=True, max_length=300, null=True)),
                ('download_url2', models.CharField(blank=True, max_length=300, null=True)),
                ('download_url3', models.CharField(blank=True, max_length=300, null=True)),
                ('description1', models.CharField(blank=True, max_length=600, null=True)),
                ('description2', models.CharField(blank=True, max_length=600, null=True)),
                ('description3', models.CharField(blank=True, max_length=600, null=True)),
                ('description4', models.CharField(blank=True, max_length=600, null=True)),
                ('title1', models.CharField(blank=True, max_length=255, null=True)),
                ('image1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image6', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
