# Generated by Django 4.1.7 on 2023-04-27 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_description1_cartoon_download_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
