# Generated by Django 4.1.7 on 2023-04-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cartoon_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='text',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
