# Generated by Django 4.1.7 on 2023-04-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_cartoon_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='text1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
